export const SET_LOAN_VALUES = "SET_LOAN_VALUES";
export const SET_FILTER_VALUES = "SET_FILTER_VALUES";
export const SET_ADDBUTTON_VISIBILITY = "SET_ADDBUTTON_VISIBILITY";
export const SET_LOAN_COPY_VALUES = "SET_LOAN_COPY_VALUES";
export const CAN_HIDE_NAV_BUTTONS = "CAN_HIDE_NAV_BUTTONS";
export const SET_PAGES = "SET_PAGES";
export const SET_SELECTED_PAGE = "SET_SELECTED_PAGE";
export const SET_DUPLICATE_PAGE_NAME = "SET_DUPLICATE_PAGE_NAME";
