export const SET_LOAN_VALUES = "SET_LOAN_VALUES";
export const SET_FILTER_VALUES = "SET_FILTER_VALUES";
export const SET_ADDBUTTON_VISIBILITY = "SET_ADDBUTTON_VISIBILITY";
export const SET_LOAN_COPY_VALUES = "SET_LOAN_COPY_VALUES";
export const SET_SERVICE_DOWN = "SET_SERVICE_DOWN";
